source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '4.2.0'
gem 'rails-api'

group :development do
  gem 'spring'
  gem 'sqlite3'
  gem 'compass'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

gem 'devise_token_auth', '0.1.30'
gem 'omniauth'
gem 'rspec-rails', '~> 3.0.0'
gem 'factory_girl_rails'
gem 'shoulda-matchers'
gem 'active_model_serializers', '~> 0.8.0'
gem 'tzinfo-data'
gem 'responders', '~> 2.0'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
